# docker-compose.yml

version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/code
    ports:
      - 8008:80
    depends_on:
      - db
    environment:
      - PYTHONPATH=/app
      - WATCHFILES_FORCE_POLLING=true
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true # This ensures that file changes are detected
  
  db:
    image: postgres:15-alpine
    container_name: local_pgdb
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      - POSTGRES_USER=fridgeai_user
      - POSTGRES_PASSWORD=fridgeai_password
      - POSTGRES_DB=fridgeai_db
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin

volumes:
  postgres_data: