# docker-compose.yml

version: '3.8'

services:
  web:
    build: backend
    volumes:
      - ./backend:/code
    ports:
      - 8008:80
    depends_on:
      - db
    environment:
      - PYTHONPATH=/app
      - WATCHFILES_FORCE_POLLING=true
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=fridgeai_user
      - POSTGRES_PASSWORD=fridgeai_password
      - POSTGRES_DB=fridgeai_db

volumes:
  postgres_data: